package com.woniu.pojo;
// Generated 2019-12-18 19:35:54 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Kaoshi generated by hbm2java
 */
public class Kaoshi implements java.io.Serializable {

	private int scid;
	private Jieduan jieduan;
	private Student student;
	private String score;
	private Date date;

	public Kaoshi() {
	}

	public Kaoshi(int scid) {
		this.scid = scid;
	}

	public Kaoshi(int scid, Jieduan jieduan, Student student, String score, Date date) {
		this.scid = scid;
		this.jieduan = jieduan;
		this.student = student;
		this.score = score;
		this.date = date;
	}

	public int getScid() {
		return this.scid;
	}

	public void setScid(int scid) {
		this.scid = scid;
	}

	public Jieduan getJieduan() {
		return this.jieduan;
	}

	public void setJieduan(Jieduan jieduan) {
		this.jieduan = jieduan;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
