package com.woniu.pojo;
// Generated 2019-12-18 19:35:54 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int sid;
	private Clazz clazz;
	private User user;
	private String sname;
	private String sex;
	private String idcard;
	private String intime;
	private String phone;
	private String address;
	private String school;
	private Set kaoshis = new HashSet(0);
	private Set kqjilus = new HashSet(0);
	private Set users = new HashSet(0);

	public Student() {
	}

	public Student(int sid) {
		this.sid = sid;
	}

	public Student(int sid, Clazz clazz, User user, String sname, String sex, String idcard, String intime,
			String phone, String address, String school, Set kaoshis, Set kqjilus, Set users) {
		this.sid = sid;
		this.clazz = clazz;
		this.user = user;
		this.sname = sname;
		this.sex = sex;
		this.idcard = idcard;
		this.intime = intime;
		this.phone = phone;
		this.address = address;
		this.school = school;
		this.kaoshis = kaoshis;
		this.kqjilus = kqjilus;
		this.users = users;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	public String getIntime() {
		return this.intime;
	}

	public void setIntime(String intime) {
		this.intime = intime;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public Set getKaoshis() {
		return this.kaoshis;
	}

	public void setKaoshis(Set kaoshis) {
		this.kaoshis = kaoshis;
	}

	public Set getKqjilus() {
		return this.kqjilus;
	}

	public void setKqjilus(Set kqjilus) {
		this.kqjilus = kqjilus;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
